---
development:
  cloud_name: deb7gemgo
  api_key: '423738583893392'
  api_secret: MESt7jlX6uxM69DZ_UaIo51tjks
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: deb7gemgo
  api_key: '423738583893392'
  api_secret: MESt7jlX6uxM69DZ_UaIo51tjks
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: deb7gemgo
  api_key: '423738583893392'
  api_secret: MESt7jlX6uxM69DZ_UaIo51tjks
  enhance_image_tag: true
  static_image_support: false
